# -*- coding: utf-8 -*-
"""Coding Loops 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/110yS5Si8xL2uR90WeGUIvw11n0ktKtz2
"""

def print_positive_numbers(numbers):
    positive_numbers = [num for num in numbers if num > 0]
    if positive_numbers:
        print("Output:", ", ".join(map(str, positive_numbers)))
    else:
        print("Output: No positive numbers found")


# Test cases
list1 = [12, -7, 5, 64, -14]
print("Input:", list1)
print_positive_numbers(list1)

list2 = [12, 14, -95, 3]
print("\nInput:", list2)
print_positive_numbers(list2)