# -*- coding: utf-8 -*-
"""Coding Loops 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xZS_LwO20YqXpT2gi2LGbiSQfxaS7tYX
"""

def fibonacci(n):
    fibonacci_series = [0, 1]  # Initialize the series with the first two Fibonacci numbers
    for i in range(2, n):
        next_number = fibonacci_series[i - 1] + fibonacci_series[i - 2]
        fibonacci_series.append(next_number)
    return fibonacci_series


# Test the function
n = 10  # Change the value of n to generate different number of Fibonacci numbers
fib_series = fibonacci(n)
print("Fibonacci series up to", n, "terms:", fib_series)